"""Snapshot test for `notebooks/comparison.ipynb` cell sources.

The committed notebook is generated by ``notebooks/_build_notebook.py``;
the build script is the readable source of truth, the ``.ipynb`` is the
renderable artifact (with executed chart outputs so reviewers see the
figures without running Jupyter).

Existing ``tests/test_notebook.py`` checks notebook **shape** — valid
nbformat, ≥3 charts, takeaways section, executed outputs present. None
of them assert the **cell sources** still match what
``_build_notebook.build_notebook()`` would write today. A tweak to any of
the ``_INTRO`` / ``_LOAD_CELL`` / ``_CAVEAT`` / ``_RECALL_CELL`` /
``_SNIPPET_CELL`` / ``_LATENCY_CELL`` / ``_TAKEAWAYS`` constants without
re-running the build script and re-executing the notebook would silently
desync the committed notebook from the script that's supposed to author it.

Same hygiene pattern as ``tests/test_summary_snapshot.py`` in this repo,
plus the snapshot tests landed across rag-production-kit,
embedding-model-shootout, llm-cost-optimizer, prompt-regression-suite.

This test compares **cell types + cell sources only**, on purpose:
- Executed ``outputs`` and ``execution_count`` are populated by
  ``jupyter nbconvert --execute`` and depend on matplotlib version /
  image-bytes determinism. ``test_notebook.py::test_notebook_executed_outputs_exist``
  already asserts the presence of outputs; pixel content isn't worth locking.
- Notebook ``metadata`` (kernelspec, language_info) is environment-dependent.

When this snapshot fails, regenerate with::

    python notebooks/_build_notebook.py
    jupyter nbconvert --to notebook --inplace --execute notebooks/comparison.ipynb

…then ``git diff notebooks/comparison.ipynb`` before committing.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

nbformat = pytest.importorskip("nbformat")

REPO_ROOT = Path(__file__).resolve().parents[1]
NOTEBOOK = REPO_ROOT / "notebooks" / "comparison.ipynb"

# Build script lives next to the notebook; import it directly.
NOTEBOOKS_DIR = REPO_ROOT / "notebooks"
if str(NOTEBOOKS_DIR) not in sys.path:
    sys.path.insert(0, str(NOTEBOOKS_DIR))

from _build_notebook import build_notebook  # type: ignore[import-not-found]  # noqa: E402

REGEN_HINT = (
    "Regenerate the notebook:\n"
    "  python notebooks/_build_notebook.py\n"
    "  jupyter nbconvert --to notebook --inplace --execute "
    "notebooks/comparison.ipynb\n"
    "Inspect with `git diff notebooks/comparison.ipynb` before committing."
)


def _cell_signature(cell) -> tuple[str, str]:
    """Strip a cell to just the dimensions this snapshot locks.

    ``nbformat`` normalizes trailing whitespace asymmetrically between the
    in-memory build path and disk read-back, so rstripping the source keeps
    the comparison meaningful (real content drift still fires) without
    flagging round-trip artifacts.
    """
    return (cell.cell_type, cell.source.rstrip())


@pytest.fixture(scope="module")
def committed_cells() -> list:
    return list(nbformat.read(NOTEBOOK, as_version=4).cells)


@pytest.fixture(scope="module")
def built_cells() -> list:
    return list(build_notebook().cells)


def test_committed_notebook_matches_build_script_cell_count(
    committed_cells: list, built_cells: list
) -> None:
    """Cell count is the cheapest first-line check; mismatch fails fast."""
    assert len(committed_cells) == len(built_cells), (
        f"Committed comparison.ipynb has {len(committed_cells)} cells but "
        f"build_notebook() now produces {len(built_cells)}.\n{REGEN_HINT}"
    )


@pytest.mark.parametrize(
    "index",
    # Range computed by collection-time `build_notebook()` so adding a cell
    # to the build script automatically grows the parametrization.
    list(range(len(build_notebook().cells))),
)
def test_committed_cell_matches_build_script(
    index: int, committed_cells: list, built_cells: list
) -> None:
    """Each cell's (cell_type, source) must match what the build script emits."""
    if index >= len(committed_cells):
        pytest.fail(
            f"Committed notebook has only {len(committed_cells)} cells; "
            f"build_notebook() emits a cell at index {index}.\n{REGEN_HINT}"
        )
    committed_type, committed_source = _cell_signature(committed_cells[index])
    built_type, built_source = _cell_signature(built_cells[index])

    assert committed_type == built_type, (
        f"Cell {index} type drift: committed is `{committed_type}`, "
        f"build_notebook() emits `{built_type}`.\n{REGEN_HINT}"
    )
    assert committed_source == built_source, (
        f"Cell {index} ({committed_type}) source drift: the committed "
        f"comparison.ipynb cell doesn't match what _build_notebook.py "
        f"now emits. This usually means a `_*_CELL` / `_INTRO` / `_CAVEAT` "
        f"/ `_TAKEAWAYS` constant was edited without rebuilding.\n"
        f"{REGEN_HINT}"
    )
